version: '3'

services:
  cine:
    build: cine
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://autocine:3306/dbautocine?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 709704
    restart: always
    depends_on:
      autocine:
          condition: service_healthy
  autocine:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 709704
      MYSQL_PASSWORD: 709704
      MYSQL_DATABASE: dbautocine
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10